### ISSUE TITLE
Getting Error: Error while checking bucket 

### ISSUE THREAD

**Issue by zaykhere** [sa7mon/S3Scanner#133]
So, I ran this command:

`s3scanner dump --dump-dir ./  --bucket bucket-name`

This is the error traceback:

```
ERROR: Error while checking bucket bucket-name
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\s3scanner.exe\__main__.py", line 7, in <module>
  File "C:\Python310\lib\site-packages\S3Scanner\__main__.py", line 219, in main
    s3service.check_perm_read(b)
  File "C:\Python310\lib\site-packages\S3Scanner\S3Service.py", line 134, in check_perm_read
    raise e
  File "C:\Python310\lib\site-packages\S3Scanner\S3Service.py", line 128, in check_perm_read
    self.s3_client.list_objects_v2(Bucket=bucket.name, MaxKeys=0)  # TODO: Compare this to doing a HeadBucket
  File "C:\Python310\lib\site-packages\botocore\client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Python310\lib\site-packages\botocore\client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (PermanentRedirect) when calling the ListObjectsV2 operation: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
```

**Comment by sa7mon** [comment]
Thank you for your bug report. I have just merged the pull request for complete re-write of this tool in Go so this issue is likely no longer applicable.

I would encourage you to try out the new version either by checking out the `main` branch or downloading the new release once I tag it. If you encounter errors with the new version, please open a new issue.
