### ISSUE TITLE
Unhandled status code

### ISSUE THREAD

**Issue by sa7mon** [sa7mon/S3Scanner#26]
bucket: ed

```
Traceback (most recent call last):
  File "./s3scanner.py", line 109, in <module>
    result = s3.checkBucket(bucket, region)
  File "/Projects/s3scanner/s3utils.py", line 35, in checkBucket
    raise ValueError("Got an unhandled status code back: " + str(r.status_code) + " for site: " + bucketName + ":" + region)
ValueError: Got an unhandled status code back: 400 for site: ed:us-west-1

```

**Comment by sa7mon** [comment]
Also `gm`. Might be a minimum character limit on bucket names.
