### ISSUE TITLE
ImportError: No module named sh

### ISSUE THREAD

**Issue by dzhenway** [sa7mon/S3Scanner#77]
~/Tools/S3Scanner$ python s3scanner.py
Traceback (most recent call last):
  File "s3scanner.py", line 12, in <module>
    import s3utils as s3
  File "/home/wayc0de/Tools/S3Scanner/s3utils.py", line 1, in <module>
    import sh
ImportError: No module named sh

**Comment by sa7mon** [comment]
I need more information. Operating system? Python version? Latest git commit ID?

**Comment by dzhenway** [comment]
Linux DESKTOP-76723ET 4.4.0-17134-Microsoft #706-Microsoft
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
a386b496ee528f942859c74eca4d7f2317a802b1

**Comment by sa7mon** [comment]
Did you follow the instructions and run `pip install -r requirements.txt`? If so, please post the results of running `pip list`

**Comment by dzhenway** [comment]
yeah im followed the instruction

`:~/Tools/S3Scanner$ pip3 list
Package             Version
------------------- -------------------
apipkg              1.5
asn1crypto          0.24.0
atomicwrites        1.3.0
attrs               19.1.0
Automat             0.6.0
awscli              1.16.166
beautifulsoup4      4.7.1
blinker             1.4
boto3               1.9.156
botocore            1.12.156
bs4                 0.0.1
certifi             2019.3.9
certstream          1.8
chardet             3.0.4
click               6.7
cloud-init          18.5
colorama            0.3.9
coloredlogs         10.0
command-not-found   0.3
configobj           5.0.6
configparser        3.7.4
constantly          15.1.0
cryptography        2.1.4
DateTime            4.3
distro-info         0.18ubuntu0.18.04.1
docutils            0.14
execnet             1.6.0
httplib2            0.9.2
humanfriendly       4.18
hyperlink           17.3.1
idna                2.8
incremental         16.10.1
Jinja2              2.10
jmespath            0.9.4
jsonpatch           1.16
jsonpointer         1.10
jsonschema          2.6.0
keyring             10.6.0
keyrings.alt        3.0
language-selector   0.1
MarkupSafe          1.0
more-itertools      7.0.0
multidict           3.3.2
netaddr             0.7.19
netifaces           0.10.4
oauthlib            2.0.6
PAM                 0.4.2
pip                 19.1.1
pipdeptree          0.10.1
pluggy              0.11.0
py                  1.8.0
pyaml               17.10.0
pyasn1              0.4.5
pyasn1-modules      0.2.1
pycrypto            2.6.1
pygobject           3.26.1
PyJWT               1.5.3
pyOpenSSL           17.5.0
pyserial            3.4
pytest              4.5.0
pytest-forked       1.0.2
pytest-xdist        1.28.0
python-apt          1.6.4
python-dateutil     2.8.0
python-debian       0.1.32
pytz                2019.1
pyxdg               0.25
PyYAML              3.13
queuelib            1.5.0
requests            2.22.0
requests-file       1.4.2
requests-unixsocket 0.1.5
rsa                 3.4.2
s3transfer          0.2.0
SecretStorage       2.3.1
secure-smtplib      0.1.1
service-identity    16.0.0
setuptools          41.0.1
sh                  1.12.14
six                 1.12.0
soupsieve           1.9.1
ssh-import-id       5.7
systemd-python      234
termcolor           1.1.0
tldextract          2.2.0
Twisted             17.9.0
ufw                 0.36
unattended-upgrades 0.1
urllib3             1.25.3
wcwidth             0.1.7
websocket-client    0.44.0
wheel               0.30.0
xmltodict           0.11.0
zope.interface      4.6.0`

**Comment by sa7mon** [comment]
Well `sh` is listed in your list of installed pip packages so I'm not sure then. Make sure you're running the tool with Python 3 if you're using pip3. Try running it again with `python3 s3scanner.py` and not `python s3scanner.py`

**Comment by dzhenway** [comment]
thats work for me
but i'd another problem when tried running it

`~/Tools/S3Scanner$ python3 s3scanner.py sites.txt
Traceback (most recent call last):
  File "s3scanner.py", line 97, in <module>
    if not s3.checkAwsCreds():
  File "/home/wayc0de/Tools/S3Scanner/s3utils.py", line 61, in checkAwsCreds
    sh.aws('sts', 'get-caller-identity', '--output', 'text', '--query', 'Account')
  File "/home/wayc0de/.local/lib/python3.6/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/home/wayc0de/.local/lib/python3.6/site-packages/sh.py", line 774, in __init__
    self.wait()
  File "/home/wayc0de/.local/lib/python3.6/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/wayc0de/.local/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /home/wayc0de/.local/bin/aws sts get-caller-identity --output text --query Account

  STDOUT:


  STDERR:
Traceback (most recent call last):
  File "/home/wayc0de/.local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/home/wayc0de/.local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/home/wayc0de/.local/lib/python3.6/site-packages/awscli/clidriver.py", line 58, in main
    driver = create_clidriver()
  File "/home/wayc0de/.local/lib/python3.6/site-packages/awscli/clidriver.py", line 68, in create_clidriver
    event_hooks=session.get_component('event_emitter'))
  File "/home/wayc0de/.local/lib/python3.6/site-packages/awscli/plugin.py", line 44, in load_plugins
    modules = _import_plugins(plugin_mapping)
  File "/home/wayc0de/.local/lib/python3.6/site-packages/awscli/plugin.py", line 61, in _import_plugins
... (552 more, please see e.stderr)`

**Comment by sa7mon** [comment]
Please run the following command in a shell and post the output: `aws sts get-caller-identity --output text --query Account`
